// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.indexActorProfile

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// IndexActorProfile_Input is the input argument to a dev.skywell.indexActorProfile call.
type IndexActorProfile_Input struct {
	// actor: Handle or DID of account to index profile of.
	Actor string `json:"actor" cborgen:"actor"`
}

// IndexActorProfile calls the XRPC method "dev.skywell.indexActorProfile".
func IndexActorProfile(ctx context.Context, c util.LexClient, input *IndexActorProfile_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "dev.skywell.indexActorProfile", nil, input, nil); err != nil {
		return err
	}

	return nil
}
