// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.defs

import (
	"github.com/bluesky-social/indigo/lex/util"
)

// Defs_FileView is a "fileView" in the dev.skywell.defs schema.
type Defs_FileView struct {
	Blob        *util.LexBlob `json:"blob" cborgen:"blob"`
	Cid         string        `json:"cid" cborgen:"cid"`
	CreatedAt   string        `json:"createdAt" cborgen:"createdAt"`
	Description *string       `json:"description,omitempty" cborgen:"description,omitempty"`
	Name        string        `json:"name" cborgen:"name"`
	Slug        string        `json:"slug" cborgen:"slug"`
	Uri         string        `json:"uri" cborgen:"uri"`
}

// Defs_ProfileView is a "profileView" in the dev.skywell.defs schema.
type Defs_ProfileView struct {
	Avatar      *string `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	Did         string  `json:"did" cborgen:"did"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	FileCount   *int64  `json:"fileCount,omitempty" cborgen:"fileCount,omitempty"`
	Handle      string  `json:"handle" cborgen:"handle"`
}
