// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.getUriFromSlug

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// GetUriFromSlug_Output is the output of a dev.skywell.getUriFromSlug call.
type GetUriFromSlug_Output struct {
	// cid: CID of the file.
	Cid string `json:"cid" cborgen:"cid"`
	// did: DID of the account that owns the file.
	Did string `json:"did" cborgen:"did"`
	// uri: URI of the file record.
	Uri string `json:"uri" cborgen:"uri"`
}

// GetUriFromSlug calls the XRPC method "dev.skywell.getUriFromSlug".
//
// slug: Slug to convert to ATProto info.
func GetUriFromSlug(ctx context.Context, c util.LexClient, slug string) (*GetUriFromSlug_Output, error) {
	var out GetUriFromSlug_Output

	params := map[string]interface{}{}
	params["slug"] = slug
	if err := c.LexDo(ctx, util.Query, "", "dev.skywell.getUriFromSlug", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
