// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.getActorFiles

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// GetActorFiles_Output is the output of a dev.skywell.getActorFiles call.
type GetActorFiles_Output struct {
	Actor    *Defs_ProfileView `json:"actor" cborgen:"actor"`
	Cursor   *string           `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Profiles []*Defs_FileView  `json:"profiles,omitempty" cborgen:"profiles,omitempty"`
}

// GetActorFiles calls the XRPC method "dev.skywell.getActorFiles".
//
// actor: Handle or DID of account to get files from.
func GetActorFiles(ctx context.Context, c util.LexClient, actor string, cursor string, limit int64) (*GetActorFiles_Output, error) {
	var out GetActorFiles_Output

	params := map[string]interface{}{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "dev.skywell.getActorFiles", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
