// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.indexActorProfile

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// IndexActorProfile calls the XRPC method "dev.skywell.indexActorProfile".
//
// actor: Handle or DID of account to index profile of.
func IndexActorProfile(ctx context.Context, c util.LexClient, actor string) error {

	params := map[string]interface{}{}
	params["actor"] = actor
	if err := c.LexDo(ctx, util.Query, "", "dev.skywell.indexActorProfile", params, nil, nil); err != nil {
		return err
	}

	return nil
}
