// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.file

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("dev.skywell.file", &File{})
} //
// RECORDTYPE: File
type File struct {
	LexiconTypeID string        `json:"$type,const=dev.skywell.file" cborgen:"$type,const=dev.skywell.file"`
	BlobRef       *util.LexBlob `json:"blobRef" cborgen:"blobRef"`
	CreatedAt     string        `json:"createdAt" cborgen:"createdAt"`
	Description   *string       `json:"description,omitempty" cborgen:"description,omitempty"`
	Name          string        `json:"name" cborgen:"name"`
}
