// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.getFileFromSlug

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// GetFileFromSlug_Output is the output of a dev.skywell.getFileFromSlug call.
type GetFileFromSlug_Output struct {
	Actor *Defs_ProfileView `json:"actor" cborgen:"actor"`
	// cid: CID of the file record.
	Cid  string         `json:"cid" cborgen:"cid"`
	File *Defs_FileView `json:"file" cborgen:"file"`
	// uri: Link to the file record.
	Uri string `json:"uri" cborgen:"uri"`
}

// GetFileFromSlug calls the XRPC method "dev.skywell.getFileFromSlug".
//
// slug: Slug to convert to ATProto info.
func GetFileFromSlug(ctx context.Context, c util.LexClient, slug string) (*GetFileFromSlug_Output, error) {
	var out GetFileFromSlug_Output

	params := map[string]interface{}{}
	params["slug"] = slug
	if err := c.LexDo(ctx, util.Query, "", "dev.skywell.getFileFromSlug", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
