// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package skywell

// schema: dev.skywell.getActorProfile

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// GetActorProfile calls the XRPC method "dev.skywell.getActorProfile".
//
// actor: Handle or DID of account to fetch profile of.
func GetActorProfile(ctx context.Context, c util.LexClient, actor string) (*Defs_ProfileView, error) {
	var out Defs_ProfileView

	params := map[string]interface{}{}
	params["actor"] = actor
	if err := c.LexDo(ctx, util.Query, "", "dev.skywell.getActorProfile", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
